version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:14.0
    environment:
      POSTGRES_DB: database_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST_AUTH_METHOD: trust
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: .
      dockerfile: docker/etc/python/Dockerfile
    restart: always
    depends_on:
      - postgres
    stdin_open: true
    tty: true
    command: ["python3", "startbot.py"]
    volumes:
      - ./api-backend:/var/www
    env_file:
      - .env